version: "3.9"

services:
  download_app:
    build: 
      context: ./download_matches
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./demo_csgo:/demo_csgo
    depends_on:
        - go
    networks:
      - monreseau

  go:
    image: golang:latest
    networks:
      - monreseau

networks:
  monreseau:
  
volumes:
  demo_csgo:
