version: "3"

services:
  flask_app:
    container_name: myapp
    restart: always
    build: ./myapp
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:server
  
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - myapp